name: PhotoLog
options:
  bundleIdPrefix: com.photolog
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  developmentLanguage: zh-Hans
  knownRegions:
    - zh-Hans
    - en

settings:
  base:
    ARCHS: arm64
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    SWIFT_VERSION: "5.9"
    PRODUCT_NAME: PhotoLog
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_KEY_CFBundleDevelopmentRegion: "zh-Hans"
    INFOPLIST_KEY_CFBundleLocalizations: ["zh-Hans", "en"]

targets:
  PhotoLog:
    type: application
    platform: macOS
    sources:
      - path: PhotoLog
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.photography"
        PRODUCT_BUNDLE_IDENTIFIER: com.photolog.app
        PRODUCT_NAME: PhotoLog
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        MARKETING_VERSION: 1.1.0
        CURRENT_PROJECT_VERSION: 2
    dependencies: []
    entitlements:
      path: PhotoLog/PhotoLog.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-only: true
        com.apple.security.files.user-selected.read-write: true

